### ISSUE TITLE
Some notes on current schema

### ISSUE THREAD

**Issue by dosumis** [NIH-NLM/cell-kn-schema#1]
Opening this as a place for shared notes.

1. We would like to be slightly more modular - with schema composed of separate modules for markers, CellSets (LinkML version CxG schema) and other content (drugs?)
1.  Currently range of slots is defined only as uriorcurie with content being indicated by examples.  Better to specify [dynamic enums](https://linkml.io/linkml/schemas/enums.html#dynamic-enums) for each.  A number of these can be based on CxG schema spec https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.3.0/schema.md. 
2. Currently no mapping of slots to OBO properties.  Not too hard to do.  Just use `slot_uri: {some curie}` e.g. https://github.com/Cellular-Semantics/cell-annotation-schema/blob/main/src/cell_annotation_schema/schema/cell_annotation_schema.yaml#L68
3. No descriptions to guide usage.  Without this it is sometimes hard to understand intent, e.g. what is difference between 'bag of genes' and 'biomarker_combination' ?
4. No fields yet marked as required - important for validation, e.g. a separate CxG cell set module might set some slots as required
5. Gene value examples do not use IDs.  Should they?

For comparison - here is the current draft CellMarker LinkML https://github.com/Cellular-Semantics/cellmark_schema/blob/main/src/cellmark_schema/schema/cellmark_schema.yaml  Also somewhat incomplete.  Might be the basis for a marker module?

**Comment by dillerm** [comment]
I'm actually working on 2-5 today. For 6, I think the answer is 'yes'. Incidentally, I was about to message you on slack about using dynamic enums. In your schema, you have a single `id` slot, the CURIE for which is restricted at the Class level. Here is an example with CellType:

```yml
CellType:
    description: "A reference to a Cell Ontology (CL) term"
    class_uri: owl:Class
    slots:
      - id
      - label
      - has_characterizing_marker_set
    slot_usage:
      id:
        range: uriorcurie
        identifier: true
        required: true
        pattern: "^CL:[0-9]{7}$"
```

Not sure if you plan on switching to dynamic enums and was going to ask about advantages/disadvantages to either approach.
